name: Build and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Composer dependencies
      run: composer install --ansi --no-progress --no-interaction --prefer-dist --no-dev

    - name: Install npm dependencies
      run: npm install

    - name: Run Grunt
      run: grunt

    - name: Create zip file
      run: zip -r wp-podro-${{ github.ref }}.zip . -x "*.git*" ".gitignore" ".distignore" "composer.*" "Gruntfile.js" "node_modules/*" "package.json" "yarn.lock" ".sass-cache/*" "assets/sass/*" ".wordpress-org/*"

    - name: Generate release notes
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: wp-podro-${{ github.ref }}
        path: wp-podro-${{ github.ref }}.zip